services:
  - type: web
    name: tunisiastore-api
    env: node
    region: frankfurt
    buildCommand: cd ../frontend && npm install && npm run build && mkdir -p ../dist/tunisia-store && cp -r dist/tunisia-store/browser ../dist/tunisia-store/
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://tunisiastore.onrender.com