build:
  command: npm install && npm run build && ls -la dist/
  publish: dist/tunisia-store/browser

services:
  - type: web
    name: tunisiastore
    env: node
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://tunisiastore.onrender.com