services:
  - type: web
    name: tunisiastore
    rootDir: backend
    env: node
    region: frankfurt
    buildCommand: npm install && cd ../frontend && npm ci && npm run build && mkdir -p ../dist/tunisia-store/browser && cp -r dist/tunisia-store/browser/* ../dist/tunisia-store/browser/
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://tunisiastore-5twr.onrender.com